### ISSUE TITLE
[TECH_TASK] Start using Redis as a backend to store user data

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#136]
** What is the problem that we're trying to solve? **
Replace postgres with storing User Json

**Task Checklist**
- [x] AccountCreateResponse to return userId
- [x] Create endpoint to return user details
- [x] Only a logged in user can ask for their details
- [x] Return 401 if user fetch is asked by users when they're not logged in
- [x] Separate out login resource from user create resource
- [x] User login should generate a new token when login is called for a logged in user
- [x] Make token expiry configurable
- [x] Ensure previous token is invalidated
- [x] Add tokens to invalidation cache with a TTL of token expiry + 1 min.
- [x] Ensure user can only login from single session
- [x] Store invalidated user tokens in Redis for the time tokens can remain valid
- [x] Update healthcheck to support redis (#65)
- [x] Can we use userId instead of username as cache value?
- [x] Logout endpoint to allow user to be invalidated
- [x] Remove grace time from invalidation key expiry
- [x] Test to check that token does get invalidated after TTL
- [x] Invalid endpoint should return 404 and not 500
- [x] Add metrics number of tokens marked invalidated. (#249)
- [x] Capture refresh count within the token (Dropped. See below)
- [x] Endpoint to refresh token upto a refresh limit (Dropped. See below)
- [x] **Refactor** : ScenarioExecutor to be functional style execution?
- [x] Investigate if documentation can be generated using annotations to parse method calls? (#331)
- [x] Run functional test on AWS deployment and if there are any issues, then either fix them or document them on a new card (#74)
- [x] For Webusers, store tokens in cookies (May be when we have webUI done?)
- [x] Force expire login using a TTL in the cache (On a separate card to deal with user expiry and token refresh (#330)
- [x] Add Redis to AWS deployment

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA

**Comment by Tyagi-Gaurav** [comment]
Instead of using Redis as a backend store, it would be used for other use cases. The Todo has been updated.

**Comment by Tyagi-Gaurav** [comment]
Don't have much information on how refresh token should work. So dropping the following two items.

- [ ] Capture refresh count within the token
- [ ] Endpoint to refresh token upto a refresh limit
