### ISSUE TITLE
[TECH_TASK] Create test for OAuth

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#137]
** What is the problem that we're trying to solve? **
Oauth use case has not been tested. Create functional test for that.

** Are there multiple approaches? If so, please document below.**
yes, for this we're going with wiremock based approach. For reference see link below.
https://tanzu.vmware.com/content/pivotal-engineering-journal/faking-oauth2-single-sign-on-in-spring-3-ways

**Task Checklist**
- [x] Create wiremock instance
- [x] Add functional test
- [x] Can we add selenium test to check UI?

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
