### ISSUE TITLE
[FEATURE] User to be logged out when user has been idle for some time 

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#330]
**Is your feature request related to a problem? Please describe.**
A user should be marked logged out when they have been idle for some time. 
In the mean time, when they raise a request and the token is about to expire within the last minute, then it should be refreshed.

**Task Checklist**
- [ ] If request comes in and the token is still valid, then fulfill request.
- [ ] If request comes in and token is within one minute of expiry, refresh token, fulfill request and return new token in response.
- [ ] If request comes in and token has expired, return 401. User needs to relogin
- [ ] Configure token expiry time
- [ ] Allow token refresh

**How should this be released (Normal, Any Special Instructions) ?** Normal

**Should this be monitored? If so, which metrics do we need?** 
- [ ] Number of tokens expired
- [ ] Number of tokens refreshed
