### ISSUE TITLE
[TECH_TASK] Investigate if documentation can be generated using annotations and parsing method calls

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#331]
** What is the problem that we're trying to solve? **
Be able to generate documentation from tests

** Are there multiple approaches? If so, please document below.**
yes, but we have chosen to go for a homegrown approach

**Task Checklist**
- [ ] Explore JavaParser way of reading method calls
- [ ] Explore aspects that we could use to check for method calls
- [ ] Inspecting all methods calls within a test that start with one of the test framework methods i.e. given(), when(), then() or and() 

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
