### ISSUE TITLE
[TECH_TASK] Use Vault to retrieve any secrets that application needs

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#46]
** What is the problem that we're trying to solve? **
The security for database and application i.e. admin username/password are written in plain text within the configuration. This should be retrieved from a secured location.

** Are there multiple approaches? If so, please document below.**
yes, we're going to explore using [Hashicorp Vault](https://www.vaultproject.io/)

**Task Checklist**
- [x] Vault Course
- [x] https://cloud.spring.io/spring-cloud-vault/reference/html/
- [x] DB secret to be retrieved Vault
- [x] Application to use salt to with password encryption (Use SHA3-256 to encrypt)
- [x] Application JWT Token key to be retrieved from Vault (Should be done using a key service instead of vault) (#56)
- [ ] Certs served by api-gateway to be retrieved from vault
- [x] Prefix all modules with `gw-`
- [x] All git guardian checks to pass
- [x] Dynamic secrets for AWS to issue user keys everytime we need to access them with very short leases.(#51)

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA

**Comment by Tyagi-Gaurav** [comment]
`Dynamic secrets for AWS to issue user keys everytime we need to access them with very short leases` should be added to the task for terraform release
