### ISSUE TITLE
[TECH_TASK] Deploy to AWS environment

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#51]
** What is the problem that we're trying to solve? **
Deploy to an external environment

** Are there multiple approaches? If so, please document below.**

**Task Checklist**
- [ ] Create cloud resources
- [ ] Deploy using commit text containing "Release"
- [ ] Be able to run remote functional tests
- [ ] Teardown after failure or success
- [ ] Be able to get failure report and logs from nodes
- [ ] Should be able to switch AWS accounts smoothly

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA

**Comment by Tyagi-Gaurav** [comment]
The pipeline has been split so that there's a single orchestrator for pushes to master/pull-request. 
Functional test and sonar are called for all the PRs/Merges. This is followed by create the release, docker image and push to ECR.

The next task is to push images to a test ECR.

**Comment by Tyagi-Gaurav** [comment]
Things needed to push image to AWS
- Access Id
- Secret
- ECR path (Check if this already exists. If not, create a manual workflow to create ECR)
- Region to push (Provision for multiple regions)

Regions could be added to matrix strategy

**Comment by Tyagi-Gaurav** [comment]
Keep getting the error `Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers` while retrieving AWS credentials from GHA.

We need to configure an OpenID connect provider on AWS. Steps are provided in the following [link](https://betterprogramming.pub/17-troubleshooting-tips-for-github-actions-workflows-43394e4f1a8a)

Summary of steps to follow so we can create a manual workflow for creating IAM roles needed for GHA.
* Add the Identity Provider (if it doesn’t exist already) - Use URL `https://token.actions.githubusercontent.com./` for github user access and audience as `sts.amazonaws.com`
* Add Role and Trust Policy: If using existing role, its federated policy should be defined as follows
* ```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::#########:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]}

* Include a separate task for Creating ECR repo (If it doesn't exist already)
* Add Inline Policy for ECR Acces. This is for logging into ECR repo using GHA `aws-actions/amazon-ecr-login@v1` 
* ```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowImagePushAndPull",
            "Effect": "Allow",
            "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:CompleteLayerUpload",
                "ecr:InitiateLayerUpload",
                "ecr:PutImage",
                "ecr:UploadLayerPart",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer"
            ],
            "Resource": "*"
        },
        {
            "Sid": "GetAuthorizationToken",
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
        }
    ]}

* Create a new GitHub Environment secret, with key `ROLE_TO_ASSUME`
* We need to specify the permission in our GitHub Actions workflow, need to add in particular, `id-token: write` permission in the caller workflow, which allows the JWT to be requested from GitHub's OIDC provider.
*

**Comment by Tyagi-Gaurav** [comment]
Still getting the same error: `Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers`
* Tried setting permissions from caller workflow
* Tried to just use `assume-role` and disable access key and secrets

**Comment by Tyagi-Gaurav** [comment]
Found that secrets declared in the repository were not accessible to the workflow. As this was a called workflow, we need to pass these variables from calling workflow.

**Comment by Tyagi-Gaurav** [comment]
What level of detail should be captured on the AWS diagram?
* VPC
* Subnets
* Communication Protocol
* Databases
* Load Balancers
* Region/Availability Zone

**Comment by Tyagi-Gaurav** [comment]
* Vault Created
* DB created
* Trying to spin up user in ec2 service which is failing to start. Unable to see logs at the moment.
* Assigned public IP and access key to ec2 cluster instance to be able to login and check the container logs as well as check why logging is not happening

**Comment by Tyagi-Gaurav** [comment]
* ECR url being passed to download was incorrect. 
* Found ECS logs under `/var/logs/ecs`. It reported that it didn't have permissions to download the image from ECR.
* First attempt: Add permissions on the repository so it can be downloaded
* Second attempt: Need to add `ecr:GetAuthorisationToken` on ECS Cluster IAM as well.

Docker container for user has started working with logging. Unable to connect to vault

**Comment by Tyagi-Gaurav** [comment]
User container unable to connect to vault even when they're in the same subnet and security group is configured correctly as well. Running Path Analyzer on AWS between the two instances.

**Comment by Tyagi-Gaurav** [comment]
- [ ] Functional test for checking UI healthcheck 
- [ ] Make sure requests can be seen in the logs
- [ ] Run a single test towards AWS that tests status for user and UI

**Comment by Tyagi-Gaurav** [comment]
After adding functional test for checking `status` endpoint of UI app, then getting `401` error.

Added various flags for disabling security on management endpoint but did not work.
management.security.enabled=false
endpoints.health.sensitive=false
endpoints.status.sensitive=false
logging.level.org.springframework.security=INFO
spring.mvc.favicon.enabled=false
logging.level.org.springframework.data=INFO

**Comment by Tyagi-Gaurav** [comment]
Found the problem with 401. WebSecurity config has a bunch of URLs specified that it permits or deny. This list was missing entry for actuator endpoints.

**Comment by Tyagi-Gaurav** [comment]
- [ ] The ports of USER and UI app are hardcoded in the nginx config. They should be externalised.

**Comment by Tyagi-Gaurav** [comment]
- [ ] To create a new ECS image for api-gateway, the image without security enabled will have to be pushed out to ECR. That change should be moved to master and pushed in a separate [card](https://github.com/Tyagi-Gaurav/GenesisWallet/issues/71).

**Comment by Tyagi-Gaurav** [comment]
While running functional tests, found that ALB is not able to route traffic to User & UI on ports 9090 & 8080 respectively because ALB listener is configured with HTTP while the security groups allow TCP. 
- [ ] Change HTTP for listener to TCP and try again

**Comment by Tyagi-Gaurav** [comment]
- [ ] Can't have a mismatch between listener protocol and healthcheck protocol. They should be same. Trying to TCP now.

**Comment by Tyagi-Gaurav** [comment]
Having TCP communication alone would not work for containers to communicate with each other. We also need to have a way for containers to find each other. One of the ways was using a CloudMap. However, that seems to be a more expensive solution. 
- [ ] Have users app installed on an EC2 instance
- [ ] UI app in ECS and API gateway to contact EC2 instance by its IP.

**Comment by Tyagi-Gaurav** [comment]
Instead of Users app created as EC2, all apps have been placed into separate ECS clusters. This way they all get ALBs and can easily reference each other using the ALB.
