### ISSUE TITLE
[TECH_TASK] Custom logging framework

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#542]
** What is the problem that we're trying to solve? **
Have a custom logging framework

**Task Checklist**
- [ ] Can we make it compatible with SLf4j or any other open source logging APIs?
- [ ] Performance tests
- [ ] Aim for microseconds response time
- [ ] Support for System out appenders
- [ ] Custom configuration file to provide logging settings (XML?)
- [ ] Support for working with annotations

**How should this be released (Normal, Any Special Instructions) ?**
- [ ] Push to github repository so we can have a version to use in main repo

**Should this be monitored? If so, which metrics do we need?**
NA
