### ISSUE TITLE
[Feature] Key service that can provide signing keys to application at startup and supports key rotation

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#56]
**Is your feature request related to a problem? Please describe.**
* We need a way to ensure that clients can read keys required for encryption and these keys should also be frequently rotated.
* The keys could either be for JWT signing or HMAC checks or anything else.

**Describe the solution you'd like**
We create a key service that can provide clients with the keys that they need.

**Describe alternatives you've considered**
Tried to use vault, but vault does not support this out of the box.

**Task Checklist**
- [ ] Create service skeleton
- [ ] Be able to deploy in docker
- [ ] Create API for admin to add, retrieve keys
- [ ] Create API for users to retrieve current key
- [ ] Test for key rotation
- [ ] Key rotation should work for old payloads as well

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
