### ISSUE TITLE
[Feature] User Registration & login via Google

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#57]
**Is your feature request related to a problem? Please describe.**
A user should be able to register using their google account

**Task Checklist**
- [x] Create a separate call to create external users
- [x] Add email as mandatory field for normal user registration
- [x] Read secrets from Github for GHA
- [x] User registration/login via google
- [x] ~~Functional test which covers journey from UI Handler in `gw-ui` to grpc call to users~~
- [x] Test to cover GRPC error scenarios
- [x] Be able to create an external user twice and no error should be thrown. Should return previous user.
- [x] Capture external system source for user
- [x] Is it possible to route `oauth2/authorization/google` call via API-Gateway
- [x] Keep timestamp as long
- [x] Ensure status endpoint works for the application (Returns ok 200 if application is up)

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
- [x] Total registrations by type (source=WEB, type=Google/Facebook/Github/linkedin/HomePage)

**Comment by Tyagi-Gaurav** [comment]
Trying to check if setting `usePlaintext()` on ManagedChannel does the trick. Seems to work.

**Comment by Tyagi-Gaurav** [comment]
There is no error in logs but still can't see records in database table

**Comment by Tyagi-Gaurav** [comment]
This happened because Mono and Future were not implemented correctly

**Comment by Tyagi-Gaurav** [comment]
New Error: `2022-12-16 13:13:38 ERROR UserService - Error occurred while creating User: DEADLINE_EXCEEDED: ClientCall started after deadline exceeded. Deadline exceeded after -25.434348700s.`

**Comment by Tyagi-Gaurav** [comment]
The above error was fixed after setting deadline before making the call instead of while initialising the blocking/unblocking stub.

**Comment by Tyagi-Gaurav** [comment]
In order to test the controller for connecting a user via `google`, we're now passing a custom mock user which creates user, roles and authorities and adds them to `SecurityContext`. 
This along with `mockOauth2Login` ensures that we get both parameters to Oauth2User and Oauth2RegisteredClient

Reference: [Spring boot and oauth2 test](https://stackoverflow.com/questions/37573361/springsecurity-withsecuritycontext-mockmvc-oauth2-always-unauthorised)

**Comment by Tyagi-Gaurav** [comment]
A few repository tests are failing due to timestamp conversion from number to Instant. It would be easier to keep the value as long in database as well as in model, and then perform conversion to instant when needed.

**Comment by Tyagi-Gaurav** [comment]
Getting the error `Invalid bean definition with name 'requestMappingHandlerAdapter' defined in class path resource` while enabling integration tests. 
Fixed it using the following spring property in `application.properties` 
`spring.main.allow-bean-definition-overriding=true`

**Comment by Tyagi-Gaurav** [comment]
Faced lot of errors in starting up vault in a test container.
* Vault container was starting up and quickly terminating before spinning up a new instance
The problem was because VaultContainer was being created within a `try-with-resources`, hence when it came out of try, the server was closed. 

* Vault container was not enforcing the policy on the login token obtained from the root token.
The problem occurred because the kv pair of database properties was not being created properly.

**Comment by Tyagi-Gaurav** [comment]
**New Error**: `The Java/XML config for Spring MVC and Spring WebFlux cannot both be enabled, e.g. via @EnableWebMvc and @EnableWebFlux, in the same application.`

**Comment by Tyagi-Gaurav** [comment]
There's a spring-webmvc dependency that was introduced for liquibase to work along with spring. We need to get rid of that dependency and see why liquibase plugin does not work.
