### ISSUE TITLE
[TECH_TASK] Create a new module for configuring mongo on the infrastructure

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#588]
**Task Checklist**
- [ ] Drop rds from dev environment
- [ ] Add mongo DB in dev
- [ ] Can vault be used to create username and password dynamically on mongoDB?

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
