### ISSUE TITLE
[TECH_TASK] Separate access and app logs for all components

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#589]
** What is the problem that we're trying to solve? **
All the components should have only two types of logs
- Access
- App 

Access logs are only logging request and responses
App logs are logging everything else

**Task Checklist**
- [x] Create configuration for access log
- [x] Create configuration for app log
- [x] Docker to show access log by default
- [x] App log to only show errors by default
- [x] Audit log to capture request method
- [x] Audit log to capture request body
- [x] Audit log to capture request headers
- [x] Audit log to capture request URI in request
- [x] Audit log to capture response status code
- [x] Audit log to capture response body
- [x] Hide Sensitive fields from payload in logs
- [x] Audit log to capture response headers\
- [x] Audit log to capture response URI
- [x] Auditing test
- [x] Tidy up cucumber test output to show only test run and put logs into a file
- [x] In-memory acceptance test for hiding sensitive fields
- [ ] Ignore static fields from builders annotation
- [x] Move pattern in AccessLogging to private static field

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
