### ISSUE TITLE
[TECH_TASK] Create annotation for various purposes

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#59]
** What is the problem that we're trying to solve? **
Reduce code writing and autogenerate boiler plate code

** Are there multiple approaches? If so, please document below.**
yes, but we're going the Java annotation approach

**Task Checklist**
- [x] Annotation to generate a logger field
- [x] Annotation to generate builder for a class
- [x] Annotation for GRPC service exceptions
- [x] Annotation for AutoConfigureDatabase 
- [x] Instantiate database beans using database configuration
- [x] Perform migration (If needed)
- [x] Perform healthcheck

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?** 
NA

**Comment by Tyagi-Gaurav** [comment]
In order to define an annotation for `@Logger`, the idea was to add a field to the class. However, Java annotations restrict modification of existing classes. [Lombok](https://projectlombok.org/) does it by hacking away into the byte code which is not an approach that would be followed in this project. 
Instead, for loggers, the current approach of defining a field in a class wherever needed would be followed.

**Comment by Tyagi-Gaurav** [comment]
Move GRPC service exception annotation to server and client interceptor changes( #14 )

**Comment by Tyagi-Gaurav** [comment]
Moving auto configure change to (#50 )
