### ISSUE TITLE
[TECH_TASK] Explore using minikube locally

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#60]
** What is the problem that we're trying to solve? **
Use minikube instead of docker locally so that the environment is more closer to production

**Task Checklist**
- [x] Ansible changes to install software locally
- [x] Install minikube
- [ ] Create pods for all services
- [ ] Be able to run functional tests for all services
- [ ] Fix ready and liveness checks for all apps
- [ ] Be able to run minikube on Github

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
