### ISSUE TITLE
[Feature] Setup observability dashboards and infrastructure

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#61]
**Task Checklist**

- [ ] Prometheus
- [ ] Grafana
- [ ] SLO/SLA dashboard for each service
- [ ] Healthcheck Dashboard
- [ ] Latency of each integration point
- [ ] Error codes
- [ ] Any circuit breakers

**How should this be released (Normal, Any Special Instructions) ?**
Normal
