### ISSUE TITLE
[TECH_TASK] Create blank spring app as reference project to use in projects. 

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#63]
** What is the problem that we're trying to solve? **
To be able to quickly perform POCs using spring

**Task Checklist**
- [ ] Create blank spring project that should just be able to start
- [ ] Basic service to add a composite object containing string & number
- [ ] Basic repo (In-memory) to create string & number
- [ ] Should be standalone
