### ISSUE TITLE
[TECH_TASK] Ensure all services have healthcheck and status endpoints exposed

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#65]
** What is the problem that we're trying to solve? **
Healthcheck and status checks for all services

**Task Checklist**

- [x] Healthcheck for database (Add db to actuator exposure)
- [x] Healthcheck for Nginx
- [x] Healthcheck for Vault
- [x] Healthcheck for user service
- [x] Healthcheck or ui
- [x] Healthcheck for Redis
- [x] ~~Allow actuator status endpoint to be accessed from ALB in **dev** environment (Allow those ports)~~
- [x] ~~Allow actuator health endpoint to be accessed from ALB in **dev** environment (Allow those ports)~~
- [x] ~~Allow actuator prometheus endpoint to be accessed from ALB in **dev** environment (Allow those ports)~~
- [x] #462
- [x] Rename /actuator/healthcheck/status to /actuator/health
- [x] Create separate endpoint for status - /actuator/status
- [x] LoggingFilterTest

**How should this be released (Normal, Any Special Instructions) ?**
Normal
