### ISSUE TITLE
[Feature] Create events in the system and send over to kafka

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#68]
**Is your feature request related to a problem? Please describe.**
Multiple places within the app need to generate events. These events should be stored in database and then sent over to kafka so they can be consumed by interested parties.

**Task Checklist**
- [ ] Setup separate table
- [ ] Generate user registration event
- [ ] Store event in database
- [ ] Read event from database and send to kafka

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
- [ ] Kafka Metrics (See [Kafka metrics](https://docs.confluent.io/platform/current/kafka/monitoring.html#server-metrics))
