### ISSUE TITLE
[TECH_TASK] Create base images for node and java apps

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#684]
** What is the problem that we're trying to solve? **
Have base images for node and Java apps which have some default configuration

**Task Checklist**
- [x] Base image for node apps
- [x] Base image for java apps
- [x] Ensure support for proto files in images of node
- [x] Custom workflow to run these in Github
- [x] Version the images using build number just like the releases
- [x] Test base images with other java projects
