### ISSUE TITLE
[TECH_TASK] Migrate from postgres over to Mongo DB

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#70]
** What is the problem that we're trying to solve? **
Moving from SQL to NoSQL database

** Are there multiple approaches? If so, please document below.**
yes, there are multiple databases to choose from. 

**Task Checklist**
- [x] Fix master build that is failing on Sonar
- [x] Create separate repository for storing data in MongoDB
- [x] Ensure functional tests are running
- [x] Create mongo DB instance locally in docker-compose
- [x] Migrate code over to use in-memory mongo DB for tests including table creation scripts
- [ ] Create terraform module for database and configure mongoDB in dev
- [x] Remove support for postgres

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
