### ISSUE TITLE
[TECH_TASK] Migrate gradle to maven

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#73]
** What is the problem that we're trying to solve? **
The dependencies in gradle are a bit hard to manage. Its much easier and simpler in maven. Other utilities that we need could be implemented using shell scripts and aliases.

**Task Checklist**
- [x] Convert main gradle file to maven
- [x] Convert subprojects to maven
- [x] Migrate dependabot configuration to use maven dependencies
- [x] Create alias (mcp) for running `maven clean package`
- [x] Create alias (mci) for running `maven clean install`
- [x] Update local scripts controlled via makefile to run builds
- [x] Update github actions to use maven
- [x] ~~Create separate card to ensure validations are getting triggered. A test within `UserJourneysTest` is disabled.~~ 

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
Not needed

**Comment by Tyagi-Gaurav** [comment]
Functional tests are not kicking off.

**Comment by Tyagi-Gaurav** [comment]
- [ ] Create Card for testing OAuth using [this](https://tanzu.vmware.com/content/pivotal-engineering-journal/faking-oauth2-single-sign-on-in-spring-3-ways) reference
