### ISSUE TITLE
[TECH_TASK] Run functional test on cloud stack

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/GenesisWallet#74]
** What is the problem that we're trying to solve? **
In order to verify the whole setup in cloud, we need to be able to run functional steps. 

** Are there multiple approaches? If so, please document below.**
No

**Task Checklist**
- [x] Debug issue of why API gateway image fails to start on AWS
- [x] Do healthcheck card (#65)
- [x] Be able to run remote functional tests after deployment
- [x] Place Vault into private subnet
- [x] Place DB into private subnet
- [x] Place User ECS into private subnet
- [x] Place UI ECS into private subnet
- [x] Place redis into private subnet
- [x] Place API Gateway ECS into **public** subnet
- [x] Teardown after failure or success
- [x] Unmap public address(es) before EC2 gateway can be detached
- [x] Can we keep only few images in ECR?
- [x] Use datasource repository for all purposes
- [x] Manual workflow to create tags

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
No

**Comment by Tyagi-Gaurav** [comment]
There is a python script that can delete images from ECR given the tag name.

**Comment by Tyagi-Gaurav** [comment]
Error in User & UI ALBs.
`The security groups for your load balancer don't allow traffic on this listener port. Manage your security groups in Security tab.`

**Comment by Tyagi-Gaurav** [comment]
User & UI ALB are unable to talk to the ECS cluster

**Comment by Tyagi-Gaurav** [comment]
Getting the following error when trying to run smoke tests on dev stack in AWS.
```
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlAuthenticationFailure: [28000] no pg_hba.conf entry for host "10.0.103.114", user "devuser", database "devDB", no encryption
```
The `no encryption` at the end could be a hint of the issue.

**Comment by Tyagi-Gaurav** [comment]
Need to check using Sandbox if the ping app can easily access DynamoDB. If so, we migrate to dynamoDB in the application and use that for storage. 
In the long run, that would be much simpler.
